### ISSUE TITLE
login/signup bug fix

### ISSUE THREAD

**Issue by wangj55** [SDD-Time-Traveler-Team/EZcalendar-Web#15]
- [x] 1. Show email/password incorrect text.

- [x] 2. Show alert text when password format is invalid in the signup page.

- [x] 3. Change email confirmation from text input field to number input field

- [x] 4. Add a sentence to tell user that we have sent them an email after registering

- [x] 5. Need to check if the confirmation code that user input is correct before redirecting to login page

- [x] 6. Emplement the function of button "x" and cancel, which is used to shut down the email confirmation code field

- [ ] 7. (Optional) Show a loading icon when waiting for logging in and confirming signup

**Comment by XiaoyuYang18** [comment]
Need to check if the confirmation code that user input is correct before jump to login page

**Comment by Anirudha-JN** [comment]
I want to solve this issue please give me this issue

**Comment by wangj55** [comment]
> I want to solve this issue please give me this issue

Hi, thank you for coming here! Unfortunately, this is a course project at our university and we are not accepting external contributions right now.

**Comment by King-Wang1** [comment]
> 1. Show email/password incorrect text.
> 2. Show alert text when password format is invalid in the signup page.
> 3. Change email confirmation from text input field to number input field
> 4. Add a sentence to tell user that we have sent them an email after registering
> 5. Need to check if the confirmation code that user input is correct before redirecting to login page
> 6. Show a loading icon when waiting for logging in and confirming signup

I have solved issue 2, and the passwrod now requires a minimum length of 8.
